({
	doInit : function(component, event, helper) {
		console.log('Inside doInit Controller');
        var action = component.get('c.getQuoteRecord');
        var quoteId = component.get('v.recordId');
         console.log('quoteId:'+quoteId);
        action.setParams({"quoteId":quoteId});
        action.setCallback(this, function(response){
         var state = response.getState();
         console.log('state:'+state); 
         if (state === "SUCCESS") {
            var resp = ""+response.getReturnValue();
             if(!resp.includes("Error:")){
                 var quoteRecord = JSON.parse(resp);
                console.log(quoteRecord);
                 console.log(quoteRecord.Name);
                 console.log(quoteRecord.SID__c);
                 console.log(quoteRecord.Status__c);
                 if((quoteRecord.Status__c === "Quote Submitted by HQ" &&(quoteRecord.Site_Plan_Status__c === '')||($A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c)))|| (quoteRecord.Status__c === "Quote Submitted to HQ" &&(quoteRecord.Site_Plan_Status__c === '')||($A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Quote Received by HQ" &&(quoteRecord.Site_Plan_Status__c === '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Quote Generated by HQ" &&(quoteRecord.Site_Plan_Status__c === '')||($A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Order Submitted" &&(quoteRecord.Site_Plan_Status__c === '')||($A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Order Management Review" &&(quoteRecord.Site_Plan_Status__c === '')||($A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Closed-Converted to New Order" &&(quoteRecord.Site_Plan_Status__c === '')||($A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c)))){ 
                     $A.get("e.force:closeQuickAction").fire();
                    var urlEvent = $A.get("e.force:navigateToURL");
                    urlEvent.setParams({
                   "url": "https://intranetuat.tams.com/VirtualApps/BusOpsWebs/SitePlanning/ActionPages/DlgCreateNewRequest.aspx?QuoteNumber="+quoteRecord.Name+ "&" + "SID="+quoteRecord.SID__c 
                    });
                    urlEvent.fire();
                     
                 }else if(
                     (quoteRecord.Status__c === "Quote Submitted by HQ" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Quote Submitted to HQ" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Quote Received by HQ" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Quote Generated by HQ" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Order Submitted" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Order Management Review" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c))) || (quoteRecord.Status__c === "Closed-Converted to New Order" &&(quoteRecord.Site_Plan_Status__c != '')||(!$A.util.isUndefinedOrNull(quoteRecord.Site_Plan_Status__c)))){
                      $A.get("e.force:closeQuickAction").fire();
                    var toastEvent = $A.get("e.force:showToast");
                  toastEvent.setParams({                      
                 "type": "error",
                 "message": "Site Drawing request already has been submitted. Please check Site Drawing Status of quote.",
                 "mode": "sticky"	
               });
               toastEvent.fire();      
                 }else{
                     $A.get("e.force:closeQuickAction").fire();
                      var toastEvent = $A.get("e.force:showToast");
                  toastEvent.setParams({                      
                 "type": "error",
                 "message": "This quote cannot be submitted for a Site Drawing Request \nbecause it does not meet requirements. \nQuote Status must be in \n..Submitted to HQ, \n..Received by HQ, \n..Generated by HQ, \n..Order Management Review, \n..Order Submitted or \n..Closed-Converted to New Order \nand there should be no Site Drawing already submitted (Site Drawing Status must be empty)",
                 "mode": "sticky"	
               });
                 }                  
             }else{
                  var toastEvent = $A.get("e.force:showToast");
                  toastEvent.setParams({
                      
                 "type": "error",
                 "message": resp,
                 "mode": "sticky"	
           });
           toastEvent.fire();
             }
            
         }
        });
         $A.enqueueAction(action);
        }
})